elasticsearch:
  hosts:
    - elasticsearch:9300
  documentIndex: docs
  documentType: document

jerseyClient:
  timeout: 5s

logging:
  level: INFO
  appenders:
    - type: console-json
      fieldNames:
        mdc: "mdc" # push Mapped Diagnostic Context into JSON sub field called "mdc"

  loggers:
    nl.knaw.huygens.pergamon: DEBUG

server:
  requestLog:
    appenders: [] # All requests are logged through logging.RequestLoggingFilter

swagger:
  resourcePackage: nl.knaw.huygens.pergamon.janus

# Location where huygensing/topmod (q.v.) is running its keyword suggestion endpoint
topModUri: http://topmod:8080
