# Base URI of the API, used in Location headers of created objects
apiUri: http://localhost:8080

documentSets:
  cocitationDocumentLimit: 84
  initialQueryLimit: 1000

elasticsearch:
  # Addresses of hosts to connect to.
  hosts:
    - localhost:9200
    #- someotherhost    # default port 9200 implied

  # Name of document index and of document type.
  documentIndex: docs
  documentType: document

  # Field definitions. Fields have name, type and xpath properties.
  # XML documents are parsed using the given XPath queries to produce values
  # for the named fields. The types are Elasticsearch index types.
  #
  # The first field is special and usually refers to a document body.
  # Tag (annotation) offsets are calculated relative to this field.
  #
  # The XPath queries must resolve to nodes or attributes.
  fields:
    - name: "body"
      type: "text"
      xpath: "/doc/body"
    - name: "title"
      type: "text"
      xpath: "/doc/title"
    - name: "author"
      type: "keyword"
      xpath: "/doc/@author"
    #- name: "pub_date"
    #  type: "date"
    #  xpath: "/doc/@date"

  # Namespace prefixes for the XPath expressions in fields.
  #namespaces:
  #  - prefix: "tei"
  #    url: "http://www.tei-c.org/ns/1.0"

jerseyClient:
  timeout: 1m

logging:
  level: INFO
  appenders:
   - type: console-json
     fieldNames:
       mdc: "mdc" # push Mapped Diagnostic Context into JSON sub field called "mdc"

  loggers:
    nl.knaw.huygens.pergamon: DEBUG

server:
  requestLog:
    appenders: [] # All requests are logged through logging.RequestLoggingFilter

storage:
  # Storage location of uploaded files.
  directory:
    original_docs

swagger:
  resourcePackage: nl.knaw.huygens.pergamon.janus

# Location where huygensing/textmod (q.v.) is running its keyword suggestion endpoint
# for example below, run the textmod docker like this:
#   $ docker run -p 8090:8080 huygensing/textmod
textModUri: http://localhost:8090
