elasticsearch:
  hosts:
    - elasticsearch:9200
  documentIndex: docs
  documentType: document

jerseyClient:
  timeout: 5m

logging:
  level: INFO
  appenders:
    - type: console-json
      fieldNames:
        mdc: "mdc" # push Mapped Diagnostic Context into JSON sub field called "mdc"

  loggers:
    nl.knaw.huygens.pergamon: DEBUG

server:
  requestLog:
    appenders: [] # All requests are logged through logging.RequestLoggingFilter

services:
  - name: "Elastic Search"
    uri: http://elasticsearch:9200
  - name: "Front End"
    uri: http://client:80/about
  - name: "Topic Modeling"
    uri: http://topmod:8080/about

swagger:
  resourcePackage: nl.knaw.huygens.pergamon.janus

# Location where huygensing/topmod (q.v.) is running its keyword suggestion endpoint
topModUri: http://topmod:8080
